export const SWFFG = {};

SWFFG.skills = {
  "astrogation" : "SWFFG.SkillAstrogation",
  "athletics" : "SWFFG.SkillAthletics",
  "computers" : "SWFFG.SkillComputer",
  "cool" : "SWFFG.SkillCool",
  "coordination" : "SWFFG.SkillCoordination",
  "cybernetics" : "SWFFG.SkillCybernetics",
  "discipline" : "SWFFG.SkillDiscipline",
  "mechanics" : "SWFFG.SkillMechanics",
  "medicine" : "SWFFG.SkillMedicine",
  "perception" : "SWFFG.SkillPerception",
  "piloting_planetary" : "SWFFG.SkillPilotingPlanetary",
  "piloting_space" : "SWFFG.SkillPilotingSpace",
  "resilience" : "SWFFG.SkillResilience",
  "skulduggery" : "SWFFG.SkillSkulduggery",
  "stealth" : "SWFFG.SkillStealth",
  "streetwise" : "SWFFG.SkillStreetwise",
  "survival" : "SWFFG.SkillSurvival",
  "vigilance" : "SWFFG.SkillVigilance",
  "brawl" : "SWFFG.SkillBrawl",
  "gunnery" : "SWFFG.SkillGunnery",
  "lightsaber" : "SWFFG.SkillLightsaber",
  "melee" : "SWFFG.SkillMelee",
  "ranged-heavy" : "SWFFG.SkillRangedHeavy",
  "ranged-light" : "SWFFG.SkillRangedLight",
  "charm" : "SWFFG.SkillCharm",
  "coercion" : "SWFFG.SkillCoercion",
  "deception" : "SWFFG.SkillDeception",
  "leadership" : "SWFFG.SkillLeadership",
  "negotiation" : "SWFFG.SkillNegotiation",
  "core-worlds" : "SWFFG.SkillCoreWorlds",
  "education" : "SWFFG.SkillEducation",
  "lore" : "SWFFG.SkillLore",
  "outer-rim" : "SWFFG.SkillOuterRim",
  "underworld" : "SWFFG.SkillUnderworld",
  "warfare" : "SWFFG.SkillWarfare",
  "xenology" : "SWFFG.SkillXenology"

}